apiVersion: v1
kind: Service
metadata:
  name: launch-ui
  labels:
    app: launch-ui
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9009
  selector:
    app: launch-ui
  externalIPs:
  - 172.31.29.239
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: launch-ui
spec:
  selector:
    matchLabels:
      app: launch-ui
  replicas: 2
  template:
    metadata:
      labels:
        app: launch-ui
    spec:
      containers:
      - name: master
        image: 953185573346.dkr.ecr.us-west-2.amazonaws.com/launchcg/launch-ui:1.0.0
        ports:
        - containerPort: 9009
      imagePullSecrets:
      - name: regcred
